
version: '3.8'

services:
  db:
    image: postgres:15
    environment:
        POSTGRES_DB: translations
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    volumes:
       - app-translator-volume:/var/lib/postgresql/data  # Volume
       - /db/init.sql:/docker-entrypoint-initdb.d/init.sql # Bind Mount
    networks:
      - db-network


  backend:
    build: ./backend
    environment: 
          DATABASE_URL: postgres://postgres:postgres@db:5432/translations

    depends_on:
      - translator
      - db
    networks:
      - db-network
      - translator-network
      - frontend-network




  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - frontend-network
  
  translator:
    image: libretranslate/libretranslate
    ports:
      - "5000:5000"


networks:
    translator-network:
      driver: bridge
    frontend-network:
      driver: bridge
    db-network:
      driver: bridge
        

volumes:
    app-translator-volume:
